default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DATABASE_USER_NAME") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") {} %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' }%>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { 'library_loan_development' } %>


test:
  <<: *default
  database: library_loan_test<%= ENV['TEST_ENV_NUMBER'] %>


production:
  <<: *default
  database: library_loan
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
